### ISSUE TITLE
Enter gửi form khi gõ "Bảng gõ tắt" on MACOS

### ISSUE THREAD

**Issue by nmquan-lifung** [lamquangminh/EVKey#11]
Hi @lamquangminh ,
Mình muồn setup cái này trên MACOS thì làm thế nào nhỉ?
Cảm ơn bạn.

_Originally posted by @nmquaan in https://github.com/lamquangminh/EVKey/issues/6#issuecomment-570990848_

**Comment by lamquangminh** [comment]
lên https://evkeyvn.com tải gói Mac về
Giải nén
Có 2 file EvkeyNSB và EVNkey thường
Nếu version của MacOS dưới 10.14 thì sử dụng NSB
Còn từ 10.14 trở lên thì sài bản thường
Thanks
MỘt số Mac nó có chế độ bảo mật như không cho cài app ngoài, không cho này nọ kia thì vào cài đặt bỏ đi ...

**Comment by nmquan-lifung** [comment]
Hi @lamquangminh , mình muốn setup cái vụ Enter submit Form như trên windows đó Ad ơi.

**Comment by lamquangminh** [comment]
Trên Windows mình cũng không làm cái Setup Form nha, 
Trên Windows mình cũng cho nó chạy trực tiếp thôi àh
Bạn tải chổ nào có cái đó là đồ fake đó

**Comment by nmquan-lifung** [comment]
Hi @lamquangminh ,
https://github.com/lamquangminh/EVKey/issues/6#issuecomment-526141063
Mình muốn setup cái này nè

**Comment by nmquaan** [comment]
Hi @lamquangminh , 
Trên MACOS làm sao set được cái này nhỉ?

> Sửa lại NPCAM=0 thành NPCAM=1 nha

Thanks!

**Comment by lamquangminh** [comment]
Bên Mac chưa có cái này bạn ơi

**Comment by nmquaan** [comment]
Hi @lamquangminh ,
Khi nào bác update cái này, bác báo em với nhé.
Thanks!

**Comment by lamquangminh** [comment]
OKE
