### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by 4dvn** [lamquangminh/EVKey#12]
## Windows
Anh ơi cái file evkau lúc update nó không ghi đè lên file cài đặt cũ nên là mỗi lần bật lên bị báo update lên bản 4.2.2.
## Mac
Bản catalina chỉ chạy được file EVKeyNSB.app còn file kia không tương thích

**Comment by lamquangminh** [comment]
bạn xoá cái file evkau đó đi và lên https://evkeyvn.com tải lại cục khác đè vào
Thanks

Còn Mac thì tuỳ cài đặt ở máy áh ..
