### ISSUE TITLE
Không gõ được tiếng Việt sau kí tự `

### ISSUE THREAD

**Issue by ltpquang** [lamquangminh/EVKey#14]
Sau khi gõ kí tự ` sẽ không gõ được tiếng Việt nữa. Ví dụ:

```
`rooif
```

Tuy nhiên nếu gõ 2 dấu ` rồi gõ chèn vào giữa thì vẫn gõ được tiếng Việt bình thường.

Mình đang dùng phiên bản 3.3.0 trên MacOS 10.15.4.
Nhu cầu này bắt nguồn từ việc mình hay soạn thảo Markdown. Mong bạn tác giả kiểm tra giúp. Cám ơn bạn.

**Comment by lamquangminh** [comment]
Cái này là do chức năng "kiểm tra chính tả" bạn có thể tắt nó đi để gõ được tiếng Việt một cách tự do
Thanks

**Comment by ltpquang** [comment]
Nhưng mà nếu như vậy thì hình như tính năng Tự động khôi phục với từ sai không còn hoạt động nữa 😅

**Comment by lamquangminh** [comment]
Tại vì kiểm tra chính tả nó check có dấu ` nó hiểu là sai chính tả, vì kí tự đó không có nghĩa trong tiếng Việt
Tiếng Việt chỉ có nháy đơn 'tiếng việt' nháy kép "tiếng Việt" ... Hoặc một số kí có thể khác
Còn kí tự ` là kí tự không có nghĩa trong tiếng việt, ghép với chữ nào nó sẽ thành sai chính tả rồi

**Comment by kimkha** [comment]
Mình nghĩ việc này cũng không khó lắm. Đằng nào thì phần mềm cũng catch được `"` và `'` rồi, nên nếu đưa thêm ký tự mới vào escape thì cũng không khó. Anyway, đây lại là câu chuyện lựa chọn của dev, cộng đồng chỉ góp ý chứ ko ép phải làm.

**Comment by kimkha** [comment]
nói thêm, ký tự ` là một ký tự mới xuất hiện trong thời đại máy tính (lúc còn viết trên giấy thì không ai xài cả). Đặc biệt, ký tự này sử dụng nhiều trong ngành lập trình phần mềm, khi cần đánh dấu một đoạn code gì đó. Ý mình là nó là một dạng new standard, nên chắc chắn bạn luôn đúng khi đề cập đến old standard khi nghĩ rằng "Tiếng Việt chỉ có nháy đơn nháy kép". Tuy nhiên, mình nghĩ ý của bạn @ltpquang là nếu được thì đi theo thời đại mới luôn 😄
