### ISSUE TITLE
Góp ý về 1 thay đổi trong EVKey

### ISSUE THREAD

**Issue by leanhducch2** [lamquangminh/EVKey#15]
Chào tác giả. Tôi có một góp ý nhỏ là tác giả nên tách tùy chọn viết hoa sau Enter dấu chấm và viết hoa chữ cái đầu câu ra 2 tùy chọn riêng vì viết hoa chữ cái đầu câu thì hơi bất tiện cho việc đăng nhập tài khoản, còn tùy chọn viết hoa sau dấu chấm thì rất hay. Cảm ơn.

**Comment by lamquangminh** [comment]
Khó để phân biệt chữ đầu câu. Nên chức năng này tạm thời không làm !!!
