### ISSUE TITLE
Lỗi khởi động cũng Windows

### ISSUE THREAD

**Issue by ghost** [lamquangminh/EVKey#16]
Mình dùng win 10 64bit, có chạy 2 account. Khi acc này chạy EVK thì khi đăng xuất chuyển sang các kìa thì EVK ko tự khởi động nữa (mình có bất setting chạy vs quyền admin và cả 2 ACC đều là Admin)

**Comment by lamquangminh** [comment]
ca này chơi khó quá :D

**Comment by cuongthm** [comment]
> Mình dùng win 10 64bit, có chạy 2 account. Khi acc này chạy EVK thì khi đăng xuất chuyển sang các kìa thì EVK ko tự khởi động nữa (mình có bất setting chạy vs quyền admin và cả 2 ACC đều là Admin)

chỉnh lại cái EVKey scheduled task cho đăng nhập bằng Administrators group chứ đừng đăng nhập tên tài khoản hiện tại
