### ISSUE TITLE
Lỗi lặp dấu accent khi gõ trên layout US International

### ISSUE THREAD

**Issue by quangvinhdo** [lamquangminh/EVKey#18]
Mình dùng bàn phím US International vì mình hay gõ tiếng Anh, Pháp, Đức,...
Khi dùng EVKey ở chế độ VNI vs layout trên, những dấu ", ^, ', `, ~,... bị lặp thành "", ^^, '', ``, ~~. Nếu dùng bàn phím ảo thì sẽ không lên dấu.
[2020-07-26 12-09-43.zip](https://github.com/lamquangminh/EVKey/files/4977151/2020-07-26.12-09-43.zip)

**Comment by lamquangminh** [comment]
Cái này có thể do lỗi keyboard layout rồi bạn ơi,
Mình chưa có cách nào chặn được
