### ISSUE TITLE
Không thiết lập được phím tắt với Space

### ISSUE THREAD

**Issue by jaredchu** [lamquangminh/EVKey#2]
Hi, vấn đề như trên title, mình muốn sử dụng Windows + Space để làm phím tắt chuyển đổi E-V nhưng không được. Xin cập nhật thêm tính năng này. Thanks in advanced!

![EVKey setting](https://i.imgur.com/jeg9tvj.png)

**Comment by lamquangminh** [comment]
ôi đệt, nay mới thấy cái post này
Mình đã làm xong ở version mới rồi nha bạn
Thanks
