### ISSUE TITLE
Lỗi version trên MacOS 10.15.6

### ISSUE THREAD

**Issue by quyctd** [lamquangminh/EVKey#20]
Hi bạn, cảm ơn bạn đã làm nên ứng dụng này, mình rất thích nó.

Hôm nay mình 1 gặp 1 issue là ứng dụng không còn cài đặt được ở trên MacOS sau khi mình nâng cấp lên version 10.15
![Screen Shot 2020-08-15 at 17 54 59](https://user-images.githubusercontent.com/30380214/90311026-2ff93f00-df21-11ea-9b53-2fe45d735a94.png)
![Screen Shot 2020-08-15 at 18 02 34](https://user-images.githubusercontent.com/30380214/90311062-85cde700-df21-11ea-8647-2eb88ade5df5.png)

Hi vọng bạn sẽ sớm fix lỗi này, cảm ơn bạn

**Comment by lamquangminh** [comment]
Ủa, bạn tải ở đâu mà nó lại hiện EVKey 17.53.03 nhỉ?
Bạn qua facebook page pm mình đi, để mình vô coi thử ?
Thanks

**Comment by quyctd** [comment]
Mình tải từ evnkeyvn.com (Trong ảnh có ghi đó ạ). 

Mình thử xoá đi và cài lại thì lại được r, ko hiểu sao @@, thanks bạn nhé
