### ISSUE TITLE
tự động chuyển bộ gõ trong vim editor?

### ISSUE THREAD

**Issue by babygau** [lamquangminh/EVKey#22]
hi,

mình muốn hỏi hiện tại có cách nào tự động chuyển bộ gõ sang tiếng anh khi chuyển từ `insert mode` sang `normal mode` ở vim không?

**Comment by lamquangminh** [comment]
Mình không rành cơ chế insert mode và normal mode ở VIM, 
Nhưng mà nếu chỉ cùng một chương trình thì không thể tự động chuyển được bạn ạ
Thanks

**Comment by hukacode** [comment]
Hi bác @lamquangminh 

Cho mình hỏi có thể đổi E/V bằng lệnh được không nhỉ?
