### ISSUE TITLE
Âm báo khi bật tắt gõ Tiếng Việt

### ISSUE THREAD

**Issue by runbeer** [lamquangminh/EVKey#23]
Âm báo hiện tại nó giống như âm báo lỗi gì đó. Nghe khá khó chịu và dễ gây hiểu lầm. Nếu đổi sang một âm báo khác thì sẽ phù hợp hơn. Góp ý nhỏ.

**Comment by lamquangminh** [comment]
Mở file setting.ini thêm vào chổ [setting] một dòng là DefSound=0
Tắt EVKey chạy lại là được bạn ạ
Thanks
