### ISSUE TITLE
Lỗi không tự start khi MacOS khởi động

### ISSUE THREAD

**Issue by Captainkoko** [lamquangminh/EVKey#24]
Vẫn còn bị lỗi không tự start khi Mac khởi động lại nhé bạn ơi. BigSur nhé.

**Comment by lamquangminh** [comment]
Trên Mac, nếu không khởi động được thì bạn bỏ chức năng tự khởi động
rồi add lại, làm vài lần sẽ được
Cái này không hiểu Mac bị cái gì nữa !
