### ISSUE TITLE
[Windows] Lỗi khi edit evkmacro.txt có chứa ký tự emoji

### ISSUE THREAD

**Issue by vangquan** [lamquangminh/EVKey#25]
**Vấn đề:** Không thể edit file evkmacro.txt để thêm vào các macro có chứa emoji. Không thể chỉnh sửa file evkmacro.txt đã chứa emoji đã nhập từ tính năng _Bảng gõ tắt_ trong phần _Cài đặt_ của EVKey. 

**Cụ thể:** Tính năng _Bảng gõ tắt_ trong phần _Cài đặt_ của EVKey giúp thêm các macro gõ tắt vào từng cái một. Vì thế, nếu cần thêm số lượng lớn, chỉnh sửa nhiều, tìm kiếm thì tôi sẽ mở trực tiếp file evkmacro.txt (bằng VS Code hoặc Notepad++) để sửa hoặc thêm vào.

1. Nếu tôi trực tiếp thêm vào file evkmacro.txt này một dòng như `grs||💎🌾🐑` rồi lưu lại và mở lại EVKey (để phần mềm load lại _Bảng gõ tắt_) thì EVKey sẽ tự tắt (crash) khi tôi gõ `grs` vào một text field nào đó.

1. Nếu tôi đã dùng tính năng _Bảng gõ tắt_ trong phần _Cài đặt_ của EVKey để thêm vào _Thay thế:_ `grs` _Cho:_ `💎🌾🐑`  rồi. Sau đó tôi edit file evkmacro.txt bằng text editor để thêm/sửa/xóa một nội dung nào đó (nhưng giữ nguyên phần macro `grs`) thì khi reload EVKey, macro `grs` không hoạt động được nữa.

**Chi tiết:**
* Windows 10.0.19042.630 (20H2)
* EVKey 4.3.7 - August 21 2020
* File evkmacro.txt  được lưu với ecoding là UTF-8 with BOM

**Mong muốn:** Cho phép chỉnh sửa file evkmacro.txt có chứa những ký tự emoji bằng phần mềm text editor chẳng hạn như VS Code và Notepad++.

**Comment by lamquangminh** [comment]
Hiện tại vẫn sử dụng emoji ở bảng gõ tắt được, nhưng phải được nhập từ bảng gõ tắt của chương trình
  Nhưng nếu bạn muốn sửa trực tiếp thì mình phải đổi định dạng của file,
  vậy thì phải thay đổi hơi bị lớn, và cũng phải tương thích với bản cũ nữa

**Comment by LeDiableCorvus** [comment]
Chúng ta có thể cập nhật/thêm tài liệu tham khảo Unicode để phát hiện các biểu tượng cảm xúc này (ví dụ: 

Mã hóa hex dec (bytes) dec binary
UTF-8 F0 9F 92 8E 240 159 146 142 4036989582 11110000 10011111 10010010 10001110
UTF-16BE D8 3D DC 8E 216 61 220 142 3627932814 11011000 00111101 11011100 10001110
UTF-16LE 3D D8 8E DC 61 216 142 220 1037602524 00111101 11011000 10001110 11011100
UTF-32BE 00 01 F4 8E 0 1 244 142 128142 00000000 00000001 11110100 10001110
UTF-32LE 8E F4 01 00 142 244 1 0 2398355712 10001110 11110100 00000001 000000000
)

**Comment by lamquangminh** [comment]
HI bạn,

Là do bạn sử dụng chương trình ko hỗ trợ full Unicode, khi chương trình mở
lên đọc sai kí tự, rồi lúc lưu xuống sai kí tự luôn nên bị lỗi,
Cách đơn giản là bạn sử dụng notepad trong Windows để chỉnh sửa là thấy oke
liền,

Thanks

Vào Th 6, 27 thg 11, 2020 vào lúc 09:03 vangquan ***@***.***>
đã viết:
