### ISSUE TITLE
[macOS] Phiên bản. 3.3.5 khi gõ dấu chấm thường xuất hiện một cách ngẫu nhiên

### ISSUE THREAD

**Issue by KennyDizi** [lamquangminh/EVKey#26]
Khi gõ văn bản, chat bằng Messenger. hoặc Zalo thì. dấu chấu xuất hiện một cách ngẫu nhiên, lỗi này tôi. gặp từ các phiên bản trước tới tận bây giờ.  Mong admin khắc phục để hoàn thiện hơn sản phẩm tuyệt vời này.

**Comment by lamquangminh** [comment]
bạn có hình ảnh không cho mình xem thử ?
Bạn có thể tick chọn "hỗ trợ bỏ dấu chính xác" để cải thiện lỗi,
Thanks

**Comment by KennyDizi** [comment]
chào anh, lỗi được thể hiện rõ ở tiêu đề và nội dung em ghi ở trên, dấu chấm xuất hiện một cách rất ngẫu nhiên, có khi liên tục, có khi lâu lâu mới bị.

**Comment by KennyDizi** [comment]
<img width="1116" alt="Screen Shot 2021-01-15 at 17 19 48" src="https://user-images.githubusercontent.com/16578966/104713091-f89ff000-5755-11eb-863f-dbde8ea491d8.png">

**Comment by TheAlemazing** [comment]
Cái này chắc bạn đang cài đặt là gõ double space thì sẽ ra dấu chấm. Bạn tắt đi thử xem. 
![image](https://user-images.githubusercontent.com/14184017/125184986-2ae56280-e24c-11eb-8c61-5797aa113bf8.png)

**Comment by lamquangminh** [comment]
> 
> 
> Cái này chắc bạn đang cài đặt là gõ double space thì sẽ ra dấu chấm. Bạn tắt đi thử xem.
> ![image](https://user-images.githubusercontent.com/14184017/125184986-2ae56280-e24c-11eb-8c61-5797aa113bf8.png)

Chắc là vậy rồi, thank bạn !!!
