### ISSUE TITLE
[macOS] Không khởi chạy được EVKey trên BigSur (Intel chipset)

### ISSUE THREAD

**Issue by HungThinh0710** [lamquangminh/EVKey#27]
Xin chào bạn tác giả @lamquangminh ,
Mình gặp phải vấn đề này khi chạy trên macOS BigSur (11.1). Đã thử một số cách trên mạng như dùng `upx`, ... Nhưng vẫn không thành công. (Đã tắt Gate Keeper / SIP)
Trước đó mình vẫn sử dụng bình thường, chỉ có hôm nay bật lên là bị như vậy - EVKey version 3.3.5.
<img width="372" alt="Screen Shot 2021-01-17 at 02 53 38" src="https://user-images.githubusercontent.com/33023931/104821542-33e21200-586f-11eb-8f74-a7d1b49c34e0.png">

**Comment by vangquan** [comment]
Dùng Terminal chạy lệnh sau
`codesign --force --deep --sign - /Applications/EVKey.app`

**Comment by HungThinh0710** [comment]
> Dùng Terminal chạy lệnh sau
> `codesign --force --deep --sign - /Applications/EVKey.app`

Đã được, cảm ơn bác nhiều! @vangquan 
<img width="857" alt="Screen Shot 2021-01-17 at 20 02 49" src="https://user-images.githubusercontent.com/33023931/104843785-fa58e780-58fe-11eb-9282-6f093720963c.png">

**Comment by lamquangminh** [comment]
Cái này thật ra chỉ cần xoá EVkey cũ hết đi
Rồi lên tải lại phiên bản mới nhất là được
Thanks

**Comment by samhwang** [comment]
Hi @lamquangminh, minh dang bi van de tuong tu voi MacOS 11.3.7, minh da download v3.3.8 tren web https://evkeyvn.com/ va ca bang Homebrew Cask, minh da thu su dung lenh `codesign --force --deep --sign - /Applications/EVKey.app` cung khong duoc luon :(

<img width="270" alt="Screen Shot 2023-02-16 at 7 32 50 pm" src="https://user-images.githubusercontent.com/4188758/219311539-9c57683a-8b30-4ab6-9ece-f1a0177963ca.png">
