### ISSUE TITLE
Về kiểu gõ Chữ Việt Nam Song Song 4.0

### ISSUE THREAD

**Issue by tommai4881** [lamquangminh/EVKey#28]
[](https://tinhte.vn/thread/cong-thuc-chu-vn-song-song-4-0-va-vi-du.3128915/)
Sao không phát triển để hỗ trợ CVNSS4,0 đi?

**Comment by lamquangminh** [comment]
Để làm gì vậy bạn ?

**Comment by tommai4881** [comment]
Thưa để thêm bộ gõ CVNSS4.0 vào trong EVKey, vì tôi đề xuất với tác giả bộ gõ này là đi gặp bạn mà

**Comment by lamquangminh** [comment]
Không hiểu ý bạn lắm ?
