### ISSUE TITLE
Tính năng "Cho phép gõ tắt" không lưu toàn bộ Marco sau khi tắt máy

### ISSUE THREAD

**Issue by Mira1409** [lamquangminh/EVKey#29]
TH1: Tự tạo bảng gõ tắt bằng tay, lưu từng dòng từng ký hiệu gõ tắt.
- Bước 1: Tạo quy tắc gõ, lưu và sử dụng bình thường. Các quy tắc gõ tắt vẫn hoạt động bình thường mặc dù thời gian hiển thị text có giật lag, chậm.
- Bước 2: Tắt máy. Khi mở lại máy thì chỉ có duy nhất 2 quy tắc được lưu còn các quy tắc gõ trước đó đều biến mất.

TH2: Tự tạo file gõ tắt Marco
- Bước 1: File có định dạng txt (Xem file đính kèm)
[evkmacro.txt](https://github.com/lamquangminh/EVKey/files/5926257/evkmacro.txt)
- Bước 2: Đẩy file lên EVkey, ấn lưu và sử dụng bình thường. Các đoạn text vẫn hiện ra khi gõ tắt.
- Bước 3: Tắt máy. Khi mở lại máy thì chỉ có duy nhất 2 quy tắc được lưu còn các quy tắc gõ trước đó đều biến mất.

![image](https://user-images.githubusercontent.com/78527952/106904703-14336080-672e-11eb-820d-e265e1226870.png)

Tên thiết bị: 
Asus Zenbook 14 UX434F
Phiên bản EVkey:
EVkey x64 - 4.3.7 - Augus 21 2020

![image](https://user-images.githubusercontent.com/78527952/106904568-eea65700-672d-11eb-80ec-661687eecdf0.png)

**Comment by lamquangminh** [comment]
Có thể bạn để EVKey ở nơi không ghi được dữ liệu, hoặc không có quyền ghi dữ liệu nên nó không lưu lại được đó bạn
Thanks

**Comment by Mira1409** [comment]
Thường thì máy tính gợi ý lưu ở ổ nào và mục nào thì em đều ấn OK luôn chứ không cân nhắc chọn folder để lưu file. Như thực tế thì em đang lưu ở đây. Không biết em nên lưu ở đâu thì phù hợp ạ? 
![image](https://user-images.githubusercontent.com/78527952/110211507-67353a80-7ec9-11eb-8dfd-84fa7220e601.png)

**Comment by lamquangminh** [comment]
Đây là gói EVKey chế của một ai đó 
EVKey của mình chỉ có bản chạy thôi, và không có gói cài đặt như vậy
Bạn lên tải lại ở trang chính https://evkeyvn.com và copy vô một nơi nào đó có quyền ghi xoá để sử dụng
Thanks
