### ISSUE TITLE
Open source

### ISSUE THREAD

**Issue by Hongarc** [lamquangminh/EVKey#3]
@lamquangminh Are you want to open source this project?

**Comment by SinhLv** [comment]
Đây là github bác ơi, github mà không open source thì up lên github làm gì? =.=

**Comment by lamquangminh** [comment]
up release,
up website
và up source liên quan tới kết nối mạng

**Comment by nguyenkien** [comment]
> Đây là github bác ơi, github mà không open source thì up lên github làm gì? =.=

Dùng github ko đồng nghĩa với opensource. Như cái repo này chứa cái website, binary của evkey, với source của cái updater. Chứ ko hề có source của evkey. Nói ngắn gọn thì evkey vẫn là closed source.

**Comment by lamquangminh** [comment]
Source EVKey do một phần dính tới bản quyền nên không up source được bạn ạ,

**Comment by heartbleeded** [comment]
Trang chủ có viết:
>  This software is distributed under the GNU GPL from the EVKey project

Bạn release source đi nếu đây là phần mềm phi lợi nhuận.

**Comment by kimkha** [comment]
@heartbleeded Mình nghĩ còn tuỳ vào định nghĩa của `This software`. Hiện tại mình vẫn có thể thấy source code của EVKAU ở đây: https://github.com/lamquangminh/EVKey/tree/master/evkau, tuy nhiên, bao nhiêu đó là chưa đủ để build app. Nếu khái niệm `This software` là EVKAU thôi thì hoàn toàn hợp lý, và đã release source. Còn những phần khác có thể dính tới bản quyền nên không public được.

**Comment by hong4rc** [comment]
EVKey có base là Unikey (có giấy phép [GNU GPL](https://vi.wikipedia.org/wiki/Gi%E1%BA%A5y_ph%C3%A9p_C%C3%B4ng_c%E1%BB%99ng_GNU)) nên sẽ là hợp lí khi open source hơn, với ko biết bạn dính bản quyền phần nào vậy, mình thấy chắc EVKey đâu cần thêm lib nào phức tạp lắm nữa nhỉ

**Comment by lamquangminh** [comment]
> 
> 
> Trang chủ có viết:
> 
> > This software is distributed under the GNU GPL from the EVKey project
> 
> Bạn release source đi nếu đây là phần mềm phi lợi nhuận.

câu này chổ nào vậy bạn ?

**Comment by lamquangminh** [comment]
> 
> 
> EVKey có base là Unikey (có giấy phép [GNU GPL](https://vi.wikipedia.org/wiki/Gi%E1%BA%A5y_ph%C3%A9p_C%C3%B4ng_c%E1%BB%99ng_GNU)) nên sẽ là hợp lí khi open source hơn, với ko biết bạn dính bản quyền phần nào vậy, mình thấy chắc EVKey đâu cần thêm lib nào phức tạp lắm nữa nhỉ

EVKey có 2 phần, GUI và Engine, GUI thời gian đầu base trên Unikey 3.6, nhưng giờ không còn nữa vì mình sửa theo ý mình hết rồi, còn engine thì lấy từ source đóng và sửa chữa lại !

**Comment by SinhLv** [comment]
Open Source hay không là quyền của dev, chứ đâu có gì cần tranh luận ở đây hả các bác :>

**Comment by lamquangminh** [comment]
> 
> 
> Open Source hay không là quyền của dev, chứ đâu có gì cần tranh luận ở đây hả các bác :>

Tuỳ theo giấy phép bạn ạ,

**Comment by heartbleeded** [comment]
> Open Source hay không là quyền của dev, chứ đâu có gì cần tranh luận ở đây hả các bác :>

Vậy thì dev cần gì phải publish lên Github nếu không phải open source? Ý đồ của dev là gì khi tự nhận phần mềm của mình được phát hành dưới GNU GPL license?

> Giấy phép Công cộng GNU là giấy phép phần mềm tự do được sử dụng rộng rãi, đảm bảo cho người dùng cuối tự do chạy, nghiên cứu, sửa đổi và chia sẻ phần mềm

Nên nhớ, phần mềm gõ tiếng Việt luôn là đối tượng hacker tấn công để gắn virus. Càng nguy hiểm hơn đối với các phần mềm mã nguồn đóng vì không có nguồn để so sánh, gây khó cho việc audit/pentest để bảo mật. Ví dụ Unikey từng bị tấn công tại đây: https://danviet.vn/nhom-hacker-sinh-tu-lenh-tan-cong-vccorp-nguy-hiem-co-nao-7777511865.htm

**Comment by kimkha** [comment]
> Như vậy mình không hiểu, dev cần gì phải publish lên Github nếu không phải open source?

Việc này theo mình thấy cũng là bình thường. Tác giả chỉ đơn giản chia sẻ source code những chỗ có thể chia sẻ được, điều này không đi ngược lại các giấy phép cũng như nguyên tắc open source: chính tác giả có quyền quyết định.

Đúng là quyết định này có thể ảnh hưởng đến việc người dùng có sử dụng sản phẩm hay không, nhưng việc đó cũng là việc tác giả đã tự cân nhắc.

Tóm lại, hoặc là user chấp nhận xài phần mềm open source một phần, hoặc là tìm kiếm một phần mềm khác, ví dụ như [GoTiengViet](https://www.trankynam.com/gotv/) (closed source) hay [OpenKey](https://github.com/tuyenvm/OpenKey) (open source).

Chọn cái nào cũng là quyền của mỗi người.

**Comment by kakakalot** [comment]
đã qua [OpenKey](https://github.com/tuyenvm/OpenKey). Tẩy chay EVKey thôi. Để đi quảng cáo bạn bè

**Comment by heartbleeded** [comment]
> đã qua [OpenKey](https://github.com/tuyenvm/OpenKey). Tẩy chay EVKey thôi. Để đi quảng cáo bạn bè

Để mình thử OpenKey.

Ngoài ra opensource gõ tiếng Việt cho macOS còn có [NAKL](https://github.com/heartbleeded/NAKL).

**Comment by SinhLv** [comment]
Yu choose yu go, no one judge :>

**Comment by lamquangminh** [comment]
> 
> 
> > > Trang chủ có viết:
> > > > This software is distributed under the GNU GPL from the EVKey project
> > > 
> > > 
> > > Bạn release source đi nếu đây là phần mềm phi lợi nhuận.
> > 
> > 
> > câu này chổ nào vậy bạn ?
> 
> Mình thấy ở trang https://evkey.org/, xin lỗi nếu đây là trang fake.
> 
Ohm trang fake bạn ạ,
> > Open Source hay không là quyền của dev, chứ đâu có gì cần tranh luận ở đây hả các bác :>
> 
> Như vậy mình không hiểu, dev cần gì phải publish lên Github nếu không phải open source? Chỉ cần để ở trang chủ là được. Mình quan tâm tới source code vì mình (và cộng đồng) có thể đóng góp, thông báo lỗi, fix bug, fork v.v.
> 
có để trang chủ mà, https://evkeyvn.com
> > Giấy phép Công cộng GNU là giấy phép phần mềm tự do được sử dụng rộng rãi, đảm bảo cho người dùng cuối tự do chạy, nghiên cứu, sửa đổi và chia sẻ phần mềm
> 
> Nên nhớ, phần mềm gõ tiếng Việt luôn là đối tượng hacker tấn công để gắn virus. Càng nguy hiểm hơn đối với các phần mềm mã nguồn đóng vì không có nguồn để so sánh, gây khó cho việc audit/pentest để bảo mật. Ví dụ Unikey từng bị tấn công tại đây: https://danviet.vn/nhom-hacker-sinh-tu-lenh-tan-cong-vccorp-nguy-hiem-co-nao-7777511865.htm
