### ISSUE TITLE
Cannot type Vietnamese after sleeping Mac for a while

### ISSUE THREAD

**Issue by ndh103** [lamquangminh/EVKey#30]
I am using EVKey with BigSur and if my mac is sleeping for a while, I cannot type Vietnames with EVKey.
Exit the app and open again cannot solve the problem, i have to restart the laptop.

**Comment by ndh103** [comment]
I have known the cause of this, it is because of Zalo, similar to the issue of Open Key that is posted here https://github.com/tuyenvm/OpenKey/issues/185

Please have a look

**Comment by lamquangminh** [comment]
Cái này không phải Zalo đâu,
Cái này là lỗi cho MacOS, 
MacOS có một chức năng bảo mật khi nhập Password vào Textbox gọi là Secure Input (SI)
Thường khi người dùng focus vào SI, thì chức năng bảo mật bật lên
Khi người dùng chuyển qua chổ khác thì chức năng bảo mật được tắt
Nhưng Mac không hoạt động tốt chức năng này
Nếu bị trên Zalo, chỉ cần Forground Zalo, rồi Background Zalo là được
Còn việc Sleep máy rồi vào không gõ được là do màn hình Login nó có chổ bảo mật
cái này lỗi do Mac

Cách chữa: 1, Có thể tìm kiếm chương trình nào có SI thì kill chương trình đó đi
Còn nếu không thể kill thì chỉ có nước Restart lại má
Thanks

**Comment by ndh103** [comment]
Thank you

**Comment by vungoctrung93** [comment]
> Cái này không phải Zalo đâu,
> Cái này là lỗi cho MacOS,
> MacOS có một chức năng bảo mật khi nhập Password vào Textbox gọi là Secure Input (SI)
> Thường khi người dùng focus vào SI, thì chức năng bảo mật bật lên
> Khi người dùng chuyển qua chổ khác thì chức năng bảo mật được tắt
> Nhưng Mac không hoạt động tốt chức năng này
> Nếu bị trên Zalo, chỉ cần Forground Zalo, rồi Background Zalo là được
> Còn việc Sleep máy rồi vào không gõ được là do màn hình Login nó có chổ bảo mật
> cái này lỗi do Mac
> 
> Cách chữa: 1, Có thể tìm kiếm chương trình nào có SI thì kill chương trình đó đi
> Còn nếu không thể kill thì chỉ có nước Restart lại má
> Thanks

Mình đã chữa được bằng cách lock screen (command + ctrl + q), sau đó mở khoá bằng mật khẩu (mình không rõ mở bằng touchID có được không nữa ).
