### ISSUE TITLE
Which folder should delete when uninstall evkey in macos?

### ISSUE THREAD

**Issue by reishou** [lamquangminh/EVKey#31]
I don't see how about uninstall evkey in your document.
Which folder we should delete when uninstall evkey?

Actually, I make a pull request 
https://github.com/Homebrew/homebrew-cask/pull/99498

But owner require a list folder should delete when uninstall evkey.
This is a example with dropbox:
https://github.com/Homebrew/homebrew-cask/blob/31cd96cc0e00dab1bff74d622e32d816bafd1f6f/Casks/dropbox.rb#L17-L35

Please clearify and tell me about it.
Thanks for supporting.

**Comment by lamquangminh** [comment]
Just delete the EVKey app !!!
