### ISSUE TITLE
Không thể gõ được tiếng việt trong 1Password

### ISSUE THREAD

**Issue by ph0ngp** [lamquangminh/EVKey#33]
Mình đang dùng:
- 1Password 7 Version 7.8 (70800000)
- EVKey cho MacOS version 3.3.6
- MacOS 10.15.7

Mình không thể dùng Evkey để gõ được tiếng việt trong phần nhập dữ liệu của 1Password

**Comment by lamquangminh** [comment]
Nhập dữ liệu Password hay thông tin khác vậy bạn ?
Nếu là password thì Mac sẽ chặn hoàn toàn bộ gõ để bảo mật
Còn nếu chổ khác không gõ được là do chương trình đó yêu cầu
Thanks

**Comment by ph0ngp** [comment]
Nhập thông tin khác không gõ đc bạn ah. Vậy chắc do app đó yêu cầu rồi. Nhưng lúc đó mình dùng bộ gõ Simple Telex của MacOS thì lại dùng được.

**Comment by lamquangminh** [comment]
Đúng rồi bạn ạ,
Simple Telex là bộ gõ của hệ thống MacOS rồi, đâu cần phải bảo mật làm gì.
