### ISSUE TITLE
Lỗi hết gõ được tiếng việt ở macos Bugs Sure (BigSur)

### ISSUE THREAD

**Issue by EUGinsane** [lamquangminh/EVKey#34]
Chào người ae, mình rất thích tool gõ tiếng việt này của bạn trên macos, kẹo nè 🍭 

Nhưng hiện tại mình và nhiều người đang gặp 1 issue đó là "mất khả năng gõ tiếng việt" trên macos Big Sur mỗi khi lock máy (ctrl + cmd + Q), và mình để ý có thể tạm thời fix bằng cách lock/unlock lại 1 lần nữa.

Catalina thì ko có bị.

Version máy của mình: MacOS Big Sur 11.2.3

Cảm ơn người ae.

**Comment by hungdev** [comment]
@Lamquangminh mình cũng không dùng được chức năng gõ tắt khi gõ password ở ứng dụng cisco anyconnect trên mac. như bạn nói thì `Cách giải quyết: tắt những chương trình đang ở trạng thái nhập Password,`. B cho mình hỏi tắt chương trình đang ở trạng thái nhập Password kiểu gì ấy nhỉ?

**Comment by lmquang79** [comment]
> @lamquangminh mình cũng không dùng được chức năng gõ tắt khi gõ password ở ứng dụng cisco anyconnect trên mac. như bạn nói thì `Cách giải quyết: tắt những chương trình đang ở trạng thái nhập Password,`. B cho mình hỏi tắt chương trình đang ở trạng thái nhập Password kiểu gì ấy nhỉ?

Hi bạn,
MacOS bảo mật ko cho bàn phím bên thứ 3 kiểm soát việc nhập password bạn ạ
Thanks
