### ISSUE TITLE
Conflict with Typinator application

### ISSUE THREAD

**Issue by hungdev** [lamquangminh/EVKey#35]
Chào bạn. Cảm ơn vì Evkey.
Typinator là phần mềm hotkey kiểu gán 1 chuỗi cho 1 ký tự nào đó xong gõ ký tự đó ra thì nó ra cả 1 chuỗi đó.
Khi dùng thi thoảng đang dùng thì gõ ko dc hoặc ko dùng được typinator.
Mình dùng macbook. Cảm ơn b.

**Comment by tansautn** [comment]
Ủa chứ vậy EV-Key có chức năng gõ tắt built-in lun mà cài cái kia chi cho cực bạn. 

Mình còn xài gõ tắt cho các mật khẩu thường xuyên lun. Thấy tiện mà. Với cả hotkey mà chỉ 1 phím. Thì conflict là đương nhiên. T nghĩ là sẽ k chỉ ev key

**Comment by hungdev** [comment]
@tansautn 
![image](https://user-images.githubusercontent.com/12009276/121846633-8423aa00-cd11-11eb-93a9-18529b1f38f5.png)
đây đúng ko bạn, nhưng nó không work nên mình mới phải dùng tool khác. Cái hotkey 1 phím thì k phải, ý mình nói đến việc gán thôi chứ bình thường mình không gán cho 1 phím mà mình sẽ gán cho 1 vài chữ. Ví dụ: he => hello
