### ISSUE TITLE
lỗi trên phiên bản 3.3.8 

### ISSUE THREAD

**Issue by tbm98** [lamquangminh/EVKey#36]
mình đã cho phép rồi nhưng vẫn báo là chưa cho phép 
macOS big sur 11.4
đã thử gỡ cài lại, cài rồi khởi động lài máy đều ko được 
<img width="763" alt="Screen Shot 2021-06-24 at 11 20 12" src="https://user-images.githubusercontent.com/52562340/123202368-a9b56e00-d4de-11eb-9e1d-3316163b8c29.png">
<img width="380" alt="Screen Shot 2021-06-24 at 11 20 19" src="https://user-images.githubusercontent.com/52562340/123202375-af12b880-d4de-11eb-845d-3fb7f8f75586.png">

**Comment by tbm98** [comment]
mình đã fix được bằng cách là bấm vào dấu trừ trong mục accessibility để xoá quyền của evkey đi. Sau đó khởi động lại cái app evkey và nó sẽ hỏi quyền lại từ đầu là được, mình ko chắc đây là bug của app hay của OS nên tạm thời chưa đóng issue :D

**Comment by lamquangminh** [comment]
Thanks bạn đã giải quyết xong vấn đề
Lỗi này nhiều nguyên nhân lắm, nhưng đã có giải quyết như vậy là hay nhất hiện tại rồi !

**Comment by tbm98** [comment]
à cho mình hỏi với, tại sao có rất nhiều bản release/version nhưng mình vào xem release chỉ có vài cái rất ít @lamquangminh

**Comment by lamquangminh** [comment]
mình chỉ để 1 bản thôi
