### ISSUE TITLE
Xung đột với Bitwarden

### ISSUE THREAD

**Issue by dinhanhthi** [lamquangminh/EVKey#37]
Trải nghiệm thực tế cho thấy EVKey (và GoTiengViet) từ lúc khởi động cùng lúc với Bitwarden (1 trình quản lý mật khẩu miễn phí) thì sẽ không hoạt động được. Trong trường hợp này chì cần restart lại Bitwarden (hoặc tắt hẳn) thì sẽ gõ bình thường được.

Đây là 1 note nhỏ hơn là 1 issue. Mình ghi trên đây nếu có ai cần.

**Comment by lamquangminh** [comment]
Trường hợp này được xem như chạy 2 bộ gõ cùng lúc rồi bạn
Cái này chắc chắn sẽ khiến cho hệ thống không ổn định
