### ISSUE TITLE
thêm option

### ISSUE THREAD

**Issue by tietnhathung** [lamquangminh/EVKey#38]
xin chào!
mình là một coder vì vậy khi sử dụng phần mềm sẽ gặp một số bất tiện như gõ "[" -> "ơ", "]" -> "ư" gõ "w" -> "ư" vậy có cách nào để loại bỏ tính năng này hay không?
cảm ơn!

**Comment by lamquangminh** [comment]
Sử dụng kiểu gõ "telex đơn giản" 
Thanks
