### ISSUE TITLE
Chữ bị bôi xanh khi gõ trên thanh tìm kiếm của trình duyệt

### ISSUE THREAD

**Issue by 8NAF** [lamquangminh/EVKey#39]
Chào anh, em đang bị một cái lỗi là khi gõ trên thanh tìm kiếm thì chữ nó sẽ bôi xanh trong tíc tắc rồi bình thường trở lại (xem gif để thấy rõ hơn).

![New-Tab-Google-Chrome-2021-10-01-13-11-21-_online-video-cutter com_](https://user-images.githubusercontent.com/62730599/135574155-7fd33f62-f9e9-4ca5-a6fb-a2bc90312e60.gif)

Hệ điều hành: Window 10 21H1
Phiên bản EVKey: v4.3.7
Các trình duyệt mà em đã thử:
| Trình duyệt | Gặp lỗi |
|-------------|---------|
| Chrome      | Có      |
| Brave       | Có      |
| Cốc Cốc     | Có      |
| Edge        | Có      |
| Blisk       | Không   |
| Vivaldi     | Không   |
| Firefox     | Không   |
| Opera       | Không   |

**Comment by lamquangminh** [comment]
Hi bạn
Tất cả các trình duyệt với Chrome Core đều xuất hiện tình trạng trên
Tình trạng trên là do cơ chế "Sửa lỗi dấu trình duyệt 2",
Nếu bạn cảm thấy khó chịu thì chuyển qua "Sửa lỗi dấu 1",
Sửa lỗi 2 sẽ sửa lỗi triệt để luôn, nhưng không sử dụng với Excel Online,
Google Sheet được
Còn Sửa lỗi 1 sẽ không triệt để trên Chrome, thỉnh thoảng sẽ bị 1 vài lần,

Bạn có thể chọn 1 hoặc 2 tuỳ muốn, nếu 1 , khi nào bi lỗi thì clear cache
trình duyệt là hết
Nếu 2 thì chấp nhận chớp xanh xanh ( mà cái này không phải hoàn toàn máy
nào cũng bị)
Thanks

Vào Th 6, 1 thg 10, 2021 vào lúc 13:16 Mai Anh Khoa <
***@***.***> đã viết:

**Comment by 8NAF** [comment]
Cảm ơn anh đã trả lời, hoá ra đó là sự khác nhau giữa Gợi ý 1 và 2.
