### ISSUE TITLE
Lỗi khi gõ 2 chữ dd -> đ ở trình duyệt chrome

### ISSUE THREAD

**Issue by xmannv** [lamquangminh/EVKey#4]
Khi muốn gõ chữ `đ` bằng cách type nhanh 2 lần chữ `d` (telex) thì sẽ ra chữ `dđ`. Lỗi này hình như bị khi trình duyệt match gợi ý với url có chứa chữ `d` đầu tiền trong history đã truy cập trước đây

![screenshot_183](https://user-images.githubusercontent.com/6252311/62843728-553be780-bce6-11e9-858f-b1686361f277.png)

![Screen Shot 2019-08-12 at 9 43 50 AM](https://user-images.githubusercontent.com/6252311/62843713-30e00b00-bce6-11e9-961f-d422f0199804.png)

**Comment by lamquangminh** [comment]
không hiểu soa máy mình ửo nhà không bao giờ bị
tức thật chứ

Vào Th 2, 12 thg 8, 2019 vào lúc 09:47 Xman <notifications@github.com> đã
viết:

**Comment by notrealdev** [comment]
cái này ko phải lỗi, mà là tính năng của chrome rồi bạn nhé
bởi vì khi bạn gõ chứ `d` thì chrome nó đề xuất lịch sử duyệt web của bạn, nên thành ra là nó sẽ là 3 chữ `ddd`
nếu trong lịch sử của bạn ko có link nào bắt đầu bằng chứ `d` thì nó sẽ hiển thị bình thường, bạn có thể tự kiểm tra.

**Comment by lamquangminh** [comment]
À hiểu rồi,
Bị lỗi đúp thành dđ hả,
Cái này hiện tại Chrome chưa có cách nào giải quyết cảm thấy ổn thoả
Và thỉnh thoảng mới bị, mà bị rồi thì bị hoài
Khi nào bị chỉ cần đóng hết tab, clear cache là sẽ hết
Thanks

**Comment by notrealdev** [comment]
không ai rảnh hơi đi viết tiếng việt trên thanh địa chỉ để tìm kiếm cả, mình nghĩ issue này nên bỏ qua
// mong các bạn thông cảm 🤩

**Comment by lamquangminh** [comment]
Mọi thứ hiện giờ có vẻ ổn với version 4.2 trở lên rồi, trên Chrome chỉ cần chọn "sửa lỗi 2" là giải quyết vấn đề chrome (trên Windows thì tốt hơn trên Mac, trên Mac một số trang vẫn không sử dụng được)
Cảm ơn mọi người rất nhiều !!!

**Comment by lamquangminh** [comment]
DONE

**Comment by ltpquang** [comment]
cám ơn bạn tác giả, chỉ vì lỗi này thôi mà mình ăn không ngon ngủ không yên 🥺bây giờ đã viên mãn rồi 🥺
