### ISSUE TITLE
lỗi gõ moiw 

### ISSUE THREAD

**Issue by ntvsp** [lamquangminh/EVKey#44]
gõ chữ " mới" trên macOs bị lỗi khi gõ "moiws"

**Comment by lamquangminh** [comment]
Bạn vui lòng chọn chức "Bỏ dấu tự do" giúp mình

Vào Th 5, 10 thg 3, 2022 vào lúc 07:49 Nguyen Tuan Vu <
***@***.***> đã viết:

**Comment by ntvsp** [comment]
> 

done tks
