### ISSUE TITLE
Gõ tiếng việt trong game Genshin Impact

### ISSUE THREAD

**Issue by notrealdev** [lamquangminh/EVKey#45]
Chào các bạn, mình đang dùng bản mới nhất nhưng ko gõ đc tiếng việt trong game
Không biết có bạn nào đang chơi game này ko nhỉ
Muốn viết đc tiếng việt thì phải dùng bộ gõ mặc định của windows thấy khá bất tiện
Nếu đc hỗ trợ thì tốt quá 😄

**Comment by z0nzjn123** [comment]
Bạn thử chạy evkey với quyền admin xem sao?

**Comment by notrealdev** [comment]
Mình để chạy với quyền admin rồi nhưng chỉ gõ đc 1 số dấu thôi, còn lại vẫn đều ra dấu ?
Chắc sai bộ gõ, mà thử đổi mấy kiểu gõ rồi vẫn ko đc

**Comment by hiepxanh** [comment]
do encoding trong game, chịu thôi :))

**Comment by notrealdev** [comment]
Bật option `Sử dụng Clipboard để gửi phím` thì đã gõ đc tiếng việt rồi
