### ISSUE TITLE
Lỗi khởi động cùng OS trên MacOS

### ISSUE THREAD

**Issue by ga4so9** [lamquangminh/EVKey#5]
Mình dùng bản 10.14.6 khi khởi động OS lên không thấy EVkey tự khởi động cùng, phải mở thủ công. Bạn check lại nhé

**Comment by lamquangminh** [comment]
giừo chắc chạy được rồi đó bạn
Thank bạn

**Comment by admdcn** [comment]
> giừo chắc chạy được rồi đó bạn
> Thank bạn

Vẫn chưa được đâu bạn ơi, mình đang dùng catalina & evkey mới nhất, đã thử kiểm tra trong mục startup đã có evkey nhưng vẫn thấy ko khởi động cùng. Mình thử xóa hẳn đi tải bản mới về vẫn thế

**Comment by fr-thi-tram** [comment]
Mình cũng bị vấn đề tương tự

**Comment by kimkha** [comment]
Mình cũng là dân dev, có thể giúp nếu bạn có hướng dẫn làm sao build trên MacOS.

**Comment by rockpham** [comment]
Nếu không khởi động cùng OS được, các bạn thử chuyển chỗ EVKey vào thư mục Applications rồi thử lại nhé.
Phần mềm ở các thư mục khác, như là thư mục Downloads sẽ không khởi động cùng OS được.
Để chắc chắn thì có thể làm thêm các bước sau:
1. Vào System Preferences -> Users & Groups -> Login Items -> kiểm tra danh sách phần mềm mở theo OS, nếu có lỗi thì xóa bớt.
2. Sau khi chuyển EVKey vào thư mục Applications xong, vào cài đặt của EVKey, tắt mở lại tùy chọn Khởi động cùng OS.

**Comment by lamquangminh** [comment]
> 
> 
> Nếu không khởi động cùng OS được, các bạn thử chuyển chỗ EVKey vào thư mục Applications rồi thử lại nhé.
> Phần mềm ở các thư mục khác, như là thư mục Downloads sẽ không khởi động cùng OS được.
> Để chắc chắn thì có thể làm thêm các bước sau:
> 
>     1. Vào System Preferences -> Users & Groups -> Login Items -> kiểm tra danh sách phần mềm mở theo OS, nếu có lỗi thì xóa bớt.
> 
>     2. Sau khi chuyển EVKey vào thư mục Applications xong, vào cài đặt của EVKey, tắt mở lại tùy chọn Khởi động cùng OS.

Git không có nút like nhỉ ?

**Comment by admdcn** [comment]
> Nếu không khởi động cùng OS được, các bạn thử chuyển chỗ EVKey vào thư mục Applications rồi thử lại nhé.
> Phần mềm ở các thư mục khác, như là thư mục Downloads sẽ không khởi động cùng OS được.
> Để chắc chắn thì có thể làm thêm các bước sau:
> 
> 1. Vào System Preferences -> Users & Groups -> Login Items -> kiểm tra danh sách phần mềm mở theo OS, nếu có lỗi thì xóa bớt.
> 2. Sau khi chuyển EVKey vào thư mục Applications xong, vào cài đặt của EVKey, tắt mở lại tùy chọn Khởi động cùng OS.

Mình cho vào thư mục application & đã khởi động okie rồi. Cảm ơn bạn nhé
