### ISSUE TITLE
[Request] Tên của release version theo cấu trúc

### ISSUE THREAD

**Issue by vn-vna** [lamquangminh/EVKey#54]
Mình đang tiến hành đưa EVKey lên package manager scoop và một yêu cầu của phía scoop đó là các phiên bản release cần có tag rõ ràng để sử dụng `version checker` của scoop và cho phép app có thể auto update.
Ví dụ như hình (được mình lấy từ repository assimp/assimp):
![image](https://user-images.githubusercontent.com/63695659/201000926-0b43fad9-7203-492c-805b-5647f6b9dc4e.png)

**Comment by doandat943** [comment]
EVKey là một ứng dụng portable vì nó chỉ có duy nhất một file exe là có thể hoạt động. Nên mình nghĩ việc cài đặt qua scoop là không thực sự thiết thực với đại đa số người dùng.

**Comment by doandat943** [comment]
Bạn có thể fork repo và release các bản dựa trên commit. Hi vọng bạn có thể fix issure này của mình bằng phiên bản 5.0.2, vì author có vẻ không quan tâm đến project này nữa. https://github.com/lamquangminh/EVKey/issues/52
