### ISSUE TITLE
Enter gửi form khi gõ "Bảng gõ tắt"

### ISSUE THREAD

**Issue by nmquaan-bigbom** [lamquangminh/EVKey#6]
Chào @lamquangminh ,
Mình hay dùng bảng gõ tắt để gõ nhanh vài cái thông tin mà làm biếng gõ nhưng dùng nhiều. Nhưng khi gõ xong `Enter` là nó gửi cái form lên luôn nên rất khó chịu. Lúc trước mình dùng `Unikey` chức năng này okie.
Hi vọng support sớm nhé.
Love Evkey!

**Comment by lamquangminh** [comment]
hi bạn
Gủi cái form lên là sao bạn êi ???

**Comment by lamquangminh** [comment]
Àh, ý là nhấn nút Enter là nó thực hiện lệnh enter luôn đó hả ?

**Comment by nmquaan-bigbom** [comment]
Hi @lamquangminh 
Đúng rồi bạn nó submit luôn cái form đó bạn.

**Comment by lamquangminh** [comment]
Àh, cái này thật ra mình có chức năng này
Nhưng do ít người sử dụng với lại cài GUI giờ rối quá mình không biết để đâu
Giờ mình hướng dẫn bạn chỉnh cái setting này
Bạn vào chổ thư mục EVKey ấy
Mở file setting.ini ra
Sửa lại NPCAM=0 thành NPCAM=1 nha
Tắt EVKey rồi chạy lại là oke bạn ạ
Thank bạn

**Comment by lamquangminh** [comment]
Nếu bạn không quen thì đưa teamview mình làm cho nhanh cũng được.

**Comment by nmquaan-bigbom** [comment]
Hi @lamquangminh ,
Mình cảm ơn bạn nhiều. Hàng ngon chất lượng quá bạn ơi.
Đã xong.
Cảm ơn bạn!

**Comment by nmquaan** [comment]
Hi @lamquangminh ,
Mình muồn setup cái này trên MACOS thì làm thế nào nhỉ?
Cảm ơn bạn.

**Comment by lamquangminh** [comment]
Bên Mac hình như không có cái này

**Comment by rattybox** [comment]
Cho em hỏi làm thế nào để không tự động mở lên file setting.ini mỗi khi mở EVKey ạ?
