### ISSUE TITLE
Không gõ tắt được với loại trừ ứng dụng

### ISSUE THREAD

**Issue by xuanhvh** [lamquangminh/EVKey#8]
Mình thấy tính năng loại trừ ứng dụng rất hay.

Ví dụ: khi mình vào sublime text để code, mình không bị gặp phiền toái với gõ tiếng việt nữa.

Nhưng mình cài gõ tắt, để lúc code trên sublime mình code cho nhanh, thì "Loại trừ ứng dụng" cũng vô tình disable luôn phần gõ tắt của mình.

Hi vọng Pro nghiên cứu lại chỗ này ạ

**Comment by lamquangminh** [comment]
Oke
Để mình sẽ thêm chức năng vẫn gõ tắt khi loại trừ ứng dụng
Thanks

Vào Th 6, 18 thg 10, 2019 vào lúc 10:37 xuanhvh <notifications@github.com>
đã viết:

**Comment by lamquangminh** [comment]
Đã xong chức năng này lâu rồi mà quên báo mất

**Comment by xuanhvh** [comment]
Mình cảm ơn Pro nhiều nhé 👯‍♂
