### ISSUE TITLE
Lỗi khi chuyển đổi mã nguồn văn bản

### ISSUE THREAD

**Issue by madokaorimura** [lamquangminh/EVKey#9]
- Sử dụng chức năng chuyển đổi mã nguồn từ TCVN3 sang Unicode gặp vấn đề.

- Một số lỗi phát hiện khi sử dụng:

1. Khi chuyển đổi (chỉ 1 lần sau khi khởi động app) thì chuyển đổi được nhưng lỗi từ đoạn văn bản chứa số về sau (ví dụ như "ngày 16 tháng x " chuyển đổi xong thì phần "16 tháng x" bị giảm cỡ phông về 1)
2. Một vài kí tự bị lỗi không chuyển đổi và bị mất đi (đưa -> đa)
3. Sau khi sử dụng chuyển đổi văn bản lần hai thì không thể nữa. Mã nguồn vẫn giữ nguyên.
(Ví dụ như từ .VnTime sang Times New Romans nhưng vẫn là font cũ, mã nguồn cũ)

- Phiên bản gặp lỗi: 4.2.2 (x86 + x64)
- Sử dụng: + WPS Office Word (free edition) + Microsoft Word (365 ProPlus)
                 + Win10 x64

> P/s: sẽ đính kèm theo ảnh hoặc video nếu có thời gian

**Comment by lamquangminh** [comment]
HI bạn,
Hiện tại EVKey bị lỗi chuyển mã liên tiếp 2 lần
Bạn cố gắng copy đoạn text xong rồi chuyển đổi
Nếu muốn chuyển đổi tiếp thì copy lại bạn ạ
Thanks

**Comment by lamquangminh** [comment]
Bạn thử lấy bản 432 về chạy thử nhé
Thanks
